clear;clc;

numProblems = 29;
numRuns     = 25;  
for p = 1:numProblems
    problemHandle = str2func( sprintf('CEC17_F%d', p) );
    
    parfor runIdx = 1:numRuns
        platemo( ...
          'algorithm', @AGEA, ...
          'problem',   problemHandle, ...
          'N',         100, ...
          'D',         30, ...
          'maxFE',     300000, ...
          'save',      1000, ...
          'metName',   {'Min_value'}, ...
          'run',       runIdx ...
        );
    end
end